plugins:
  - name: serve
    init: |
      const express = require('express');
      const path = require('path');
      const server = express();

      server.use('/', express.static('docs/_site'));
      server.use('*', (req, res) => {
        res.sendFile(path.join(__dirname, 'docs/_site/index.html'));
      });

      server.listen(process.env.PORT || 3000, () => {
        console.log(`Docsify server started at http://localhost:${process.env.PORT || 3000}`);
      });
